"""Add location/instagram/youtube to influencer

Revision ID: f24f6a569dad
Revises: 13d677506df8
Create Date: 2025-05-08 03:48:01.875385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f24f6a569dad'
down_revision = '13d677506df8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('influencer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('instagram', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('youtube', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('influencer', schema=None) as batch_op:
        batch_op.drop_column('youtube')
        batch_op.drop_column('instagram')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
